name: elementary
description: MVVM-inspired architectural library.
version: 0.0.3-dev.5
repository: "https://github.com/surfstudio/flutter-elementary"
issue_tracker: "https://github.com/surfstudio/flutter-elementary/issues"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.2.0
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true