name: profile
version: "0.0.1-dev.0"
description: Example of using Elementary with Bloc.
publish_to: none

dependencies:
  async: ^2.8.2
  bloc: ^8.0.2
  elementary: ^1.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  logger: ^1.1.0
  provider: ^6.0.1
  shimmer: ^2.0.0
  surf_logger: ^1.0.1
  yandex_mapkit: ^2.0.6

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^5.5.1
  elementary_test: ^1.0.1
  flutter_test:
    sdk: flutter
  mjk_lint_rules: ^1.0.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
