name: profile
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  bloc: ^8.0.2
  dio: ^4.0.4
  elementary: ^1.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  logger: ^1.1.0
  provider: ^6.0.1
  shimmer: ^2.0.0
  surf_logger: ^1.0.1
  yandex_mapkit: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^4.7.0
  elementary_test: ^1.0.1
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.4.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  uses-material-design: true
